# Series Attributes and Methods

Pandas Series come with various attributes and methods to help you manipulate and analyze data effectively. Here are a few essential ones:

<b> values: </b> Returns the Series data as a NumPy array. 

<b> index: </b> Returns the index (labels) of the Series.

<b> shape: </b>  Returns a tuple representing the dimensions of the Series.

<b> size:  </b> Returns the number of elements in the Series.

<b> mean(), sum(), min(), max():  </b> Calculate summary statistics of the data.

<b> unique(), nunique():  </b> Get unique values or the number of unique values.

<b> sort_values(), sort_index():  </b>  Sort the Series by values or index labels.

<b> isnull(), notnull():  </b> Check for missing (NaN) or non-missing values.

<b> apply():  </b> Apply a custom function to each element of the Series.

# What is a DataFrames?

A DataFrame is a two-dimensional labeled data structure with columns of potentially different data types. 

Think of it as a table where each column represents a variable, and each row represents an observation or data point. 

DataFrames are suitable for a wide range of data, including structured data from CSV files, Excel spreadsheets, SQL databases, and more.

In [2]:
import pandas as pd

# Creating a DataFrame from a dictionary
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 28],
        'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago']}

df = pd.DataFrame(data)

print(df)

      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles
3    David   28        Chicago

## Column Selection
You can select a single column from a DataFrame by specifying the column name within double brackets.

Multiple columns can be selected in a similar manner, creating a new DataFrame.

In [3]:
print(df['Name'])  # Access the 'Name' column

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object

## Accessing Rows
You can access rows by their index using .iloc[] or by label using .loc[].

In [10]:
print(df.iloc[2])   # Access the third row by position
print("-------")
print(df.loc[1])    # Access the second row by label

Name        Charlie
Age              35
City    Los Angeles
Name: 2, dtype: object
-------
Name              Bob
Age                30
City    San Francisco
Name: 1, dtype: object

## slicing
You can slice DataFrames to select specific rows and columns.

In [5]:
print(df[['Name', 'Age']])  # Select specific columns
print("-------------")
print(df[1:3])             # Select specific rows

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   28
-------------
      Name  Age           City
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles

## Finding Unique Elements
Use the unique method to determine the unique elements in a column of a DataFrame.

In [12]:
unique_dates = df['Age'].unique()
print(unique_dates)

[25 30 35 28]

## Conditional Filtering
You can filter data in a DataFrame based on conditions using inequality operators.For instance, you can filter albums released after a certain year.

In [15]:
high_above_102 = df[df['Age'] > 25]
print(high_above_102)

      Name  Age           City
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles
3    David   28        Chicago

## Saving DataFrames
To save a DataFrame to a CSV file, use the to_csv method and specify the filename with a “.csv” extension.Pandas provides other functions for saving DataFrames in different formats.

In [8]:
df.to_csv('trading_data.csv', index=False)

# DataFrame Attributes and Methods

<b> shape: </b>  Returns the dimensions (number of rows and columns) of the DataFrame.

<b> info():  </b>  Provides a summary of the DataFrame, including data types and non-null counts.

<b> describe():  </b>   Generates summary statistics for numerical columns.

<b> head(), tail():  </b>  Displays the first or last n rows of the DataFrame.

<b> mean(), sum(), min(), max():  </b>  Calculate summary statistics for columns.

<b> sort_values():  </b>  Sort the DataFrame by one or more columns.

<b> groupby():  </b>  Group data based on specific columns for aggregation.

<b> fillna(), drop(), rename():  </b>  Handle missing values, drop columns, or rename columns.

<b> apply():  </b>  Apply a function to each element, row, or column of the DataFrame.

In [16]:
import pandas as pd

In [43]:
x = {'Name': ['Rose','John', 'Jane', 'Mary'], 
     'ID': [1, 2, 3, 4], 
     'Department': ['Architect Group', 'Software Group', 'Design Team', 'Infrastructure'], 
      'Salary':[100000, 80000, 50000, 60000]}

#casting the dictionary to a DataFrame
df = pd.DataFrame(x)

#display the result df
df

   Name  ID       Department  Salary
0  Rose   1  Architect Group  100000
1  John   2   Software Group   80000
2  Jane   3      Design Team   50000
3  Mary   4   Infrastructure   60000

In [19]:
x= df[['ID']]
x

   ID
0   1
1   2
2   3
3   4

In [20]:
type(x)

pandas.core.frame.DataFrame

In [22]:
z=df[['Department','Salary','ID']]
z

        Department  Salary  ID
0  Architect Group  100000   1
1   Software Group   80000   2
2      Design Team   50000   3
3   Infrastructure   60000   4

In [23]:
a = {'Student':['David', 'Samuel', 'Terry', 'Evan'],
     'Age':['27', '24', '22', '32'],
     'Country':['UK', 'Canada', 'China', 'USA'],
     'Course':['Python','Data Structures','Machine Learning','Web Development'],
     'Marks':['85','72','89','76']}
df1 = pd.DataFrame(a)
df1

  Student Age Country            Course Marks
0   David  27      UK            Python    85
1  Samuel  24  Canada   Data Structures    72
2   Terry  22   China  Machine Learning    89
3    Evan  32     USA   Web Development    76

In [36]:
df1=pd.DataFrame(a)
b=df1[["Marks"]]
b

  Marks
0    85
1    72
2    89
3    76

In [37]:
c=df1[["Country","Course"]]
c

  Country            Course
0      UK            Python
1  Canada   Data Structures
2   China  Machine Learning
3     USA   Web Development

In [38]:
x = df1['Student']
x

0     David
1    Samuel
2     Terry
3      Evan
Name: Student, dtype: object

In [31]:
type(x)

pandas.core.series.Series

### Exercise 2: <code>loc()</code> and <code>iloc()</code> functions

<code>loc()</code> is a label-based data selecting method which means that we have to pass the name of the row or column that we want to select. This method includes the last element of the range passed in it.

Simple syntax for your understanding: 

 - loc[row_label, column_label]

<code>iloc()</code> is an indexed-based selecting method which means that we have to pass an integer index in the method to select a specific row/column. This method does not include the last element of the range passed in it.

Simple syntax for your understanding: 
   
 - iloc[row_index, column_index]

<h4 id="data">Let us see some examples on the same.</h4>

In [44]:
df.iloc[0, 0]

'Rose'

In [45]:
df.iloc[0,2]

'Architect Group'

In [46]:
df.loc[0, 'Salary']

np.int64(100000)

In [47]:
df2=df
df2=df2.set_index("Name")

In [48]:
df2.head()

      ID       Department  Salary
Name
Rose   1  Architect Group  100000
John   2   Software Group   80000
Jane   3      Design Team   50000
Mary   4   Infrastructure   60000

In [49]:
df2.loc['Jane', 'Salary']

np.int64(50000)

In [50]:
df2.loc['Jane', 'Department']

'Design Team'

In [51]:
df2.iloc[3,2]

np.int64(60000)

### Slicing

Slicing uses the [] operator to select a set of rows and/or columns from a DataFrame.

To slice out a set of rows, you use this syntax: data[start:stop], 

here the start represents the index from where to consider, and stop represents the index one step BEYOND the row you want to select. You can perform slicing using both the index and the name of the column.

> NOTE: When slicing in pandas, the start bound is included in the output.

So if you want to select rows 0, 1, and 2 your code would look like this: df.iloc[0:3].

It means you are telling Python to start at index 0 and select rows 0, 1, 2 up to but not including 3.

> NOTE: Labels must be found in the DataFrame or you will get a KeyError.

Indexing by labels(i.e. using <code>loc()</code>) differs from indexing by integers (i.e. using <code>iloc()</code>). With <code>loc()</code>, both the start bound and the stop bound are inclusive. When using <code>loc()</code>, integers can be used, but the integers refer to the index label and not the position. 

For example, using <code>loc()</code> and select 1:4 will get a different result than using <code>iloc()</code> to select rows 1:4.

<h4 id="data">We can also select a specific data value using a row and column location within the DataFrame and iloc indexing.

In [52]:
df.iloc[0:2, 0:3]

   Name  ID       Department
0  Rose   1  Architect Group
1  John   2   Software Group

In [53]:
# let us do the slicing using old dataframe df

df.iloc[0:2, 0:3]

   Name  ID       Department
0  Rose   1  Architect Group
1  John   2   Software Group

In [54]:
#let us do the slicing using loc() function on new dataframe df2 where index column is Name having labels: Rose, John and Jane
df2.loc['Rose':'Jane', 'ID':'Department']

      ID       Department
Name
Rose   1  Architect Group
John   2   Software Group
Jane   3      Design Team

In [55]:
df.loc[2:3,'Name':'Department']

   Name  ID      Department
2  Jane   3     Design Team
3  Mary   4  Infrastructure

The table has one row for each product and several columns.

<ul>
    <li><b>OrderID</b>: A unique identifier for each order</li>
    <li><b>Product</b>: The name of the product purchased</li>
    <li><b>Category</b>: The category to which the product belongs (e.g., Electronics, Furniture, Stationery)</li>
    <li><b>Quantity</b>: The number of units purchased for that product</li>
    <li><b>Price</b>: The price per unit of the product</li>
    <li><b>Total</b>: The total cost for the product (calculated as Quantity × Price)</li>
    <li><b>OrderDate</b>: The date when the order was placed</li>
    <li><b>CustomerCity</b>: The city where the customer resides</li>
    
</ul>

You can see the dataset here:

<font size="1">
<table style="font-size:medium; border:1px solid black; border-collapse:collapse;">
  <tr>
    <th>OrderID</th>
    <th>Product</th>
    <th>Category</th>
    <th>Quantity</th>
    <th>Price</th>
    <th>Total</th>
    <th>OrderDate</th>
    <th>CustomerCity</th>
  </tr>
  <tr>
    <td>1</td>
    <td>Laptop</td>
    <td>Electronics</td>
    <td>2</td>
    <td>800</td>
    <td>1600</td>
    <td>2022-01-10</td>
    <td>New York</td>
  </tr>
  <tr>
    <td>2</td>
    <td>Smartphone</td>
    <td>Electronics</td>
    <td>3</td>
    <td>600</td>
    <td>1800</td>
    <td>2022-02-15</td>
    <td>Los Angeles</td>
  </tr>
  <tr>
    <td>3</td>
    <td>Desk Chair</td>
    <td>Furniture</td>
    <td>5</td>
    <td>150</td>
    <td>750</td>
    <td>2022-03-12</td>
    <td>Chicago</td>
  </tr>
  <tr>
    <td>4</td>
    <td>Notebook</td>
    <td>Stationery</td>
    <td>10</td>
    <td>2</td>
    <td>20</td>
    <td>2022-04-05</td>
    <td>Houston</td>
  </tr>
  <tr>
    <td>5</td>
    <td>Monitor</td>
    <td>Electronics</td>
    <td>1</td>
    <td>300</td>
    <td>300</td>
    <td>2022-05-21</td>
    <td>Miami</td>
  </tr>
</table>
</font>

In [56]:
%pip install xlrd openpyxl

Collecting xlrd
  Downloading xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: xlrd, et-xmlfile, openpyxl

   ---------------------------------------- 0/3 [xlrd]
   ---------------------------------------- 0/3 [xlrd]
   ------------- -------------------------- 1/3 [et-xmlfile]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   -------------------------- ------------- 2/3 [openpyxl]
   ---------------------------------------- 3/3 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5 xlrd-2.0.2
Note: you may need to restart the kernel to use updated packages.

In [69]:
import pandas as pd
df = pd.read_csv("Product_sales.csv")

In [70]:
df.head()

,OrderID,Product,Category,Quantity,Price,Total,OrderDate,CustomerCity
0,1,Laptop,Electronics,2,800,1600,2022-01-10,New York
1,2,Smartphone,Electronics,3,600,1800,2022-02-15,Los Angeles
2,3,Desk Chair,Furniture,5,150,750,2022-03-12,Chicago
3,4,Notebook,Stationery,10,2,20,2022-04-05,Houston
4,5,Monitor,Electronics,1,300,300,2022-05-21,Miami

In [73]:
x=df[["Quantity"]]
x

   Quantity
0         2
1         3
2         5
3        10
4         1

In [75]:
x=df[["Product"]]
x

      Product
0      Laptop
1  Smartphone
2  Desk Chair
3    Notebook
4     Monitor

In [76]:
x = df[['Quantity']]
type(x)

pandas.core.frame.DataFrame

In [77]:
y = df[['Product','Category', 'Quantity']]
y

      Product     Category  Quantity
0      Laptop  Electronics         2
1  Smartphone  Electronics         3
2  Desk Chair    Furniture         5
3    Notebook   Stationery        10
4     Monitor  Electronics         1

In [78]:
# Access the value on the first row and the first column

df.iloc[0, 0]

np.int64(1)

In [79]:
# Access the value on the second row and the first column

df.iloc[1,0]

np.int64(2)

In [80]:
df.iloc[0,2]

'Electronics'

In [81]:
df.iloc[1,2]

'Electronics'

In [82]:
df.loc[0, 'Product']

'Laptop'

In [83]:
df.loc[1, 'Product']

'Smartphone'

In [84]:
df.loc[1, 'CustomerCity']

'Los Angeles'

In [85]:
df.loc[1, 'Total']

np.int64(1800)

In [86]:
df.iloc[0:2, 0:3]

   OrderID     Product     Category
0        1      Laptop  Electronics
1        2  Smartphone  Electronics

In [87]:
df.loc[0:2, 'OrderID':'Category']

   OrderID     Product     Category
0        1      Laptop  Electronics
1        2  Smartphone  Electronics
2        3  Desk Chair    Furniture

In [88]:
q = df[['Price']]
q

   Price
0    800
1    600
2    150
3      2
4    300

In [89]:
q = df[['Product', 'Category']]
q

      Product     Category
0      Laptop  Electronics
1  Smartphone  Electronics
2  Desk Chair    Furniture
3    Notebook   Stationery
4     Monitor  Electronics

In [90]:
df.iloc[1, 2]

'Electronics'

Use the following list to convert the dataframe index <code>df</code> to characters and assign it to <code>df_new</code>; find the element corresponding to the row index <code>a</code> and column  <code>'CustomerCity'</code>. Then select the rows <code>a</code> through <code>d</code> for the column  <code>'CustomerCity'</code>

In [91]:
new_index=['a','b','c','d','e']
df_new=df
df_new.index=new_index
df_new.loc['a', 'CustomerCity']
df_new.loc['a':'d', 'CustomerCity']

a       New York
b    Los Angeles
c        Chicago
d        Houston
Name: CustomerCity, dtype: object